### ISSUE TITLE
Pictures for monsters without banner pics

### ISSUE THREAD

**Issue by EFox2413** [EFox2413/initiumGrease#18]
1. Identify all monsters currently without pictures
2. Create artwork that matches the game style for each monster

**Comment by EFox2413** [comment]
Goblin Archer

**Comment by CarnyMarcTu** [comment]
knoll troll and the green dragons

**Comment by CarnyMarcTu** [comment]
acolyte

**Comment by EFox2413** [comment]
Specification:
- 728x211 px
- JPEG format

Examples:
- https://www.playinitium.com/images/npc-murloc.jpg
